language: cpp
compiler:
  - gcc
  - clang

os:
  -linux

dist: trusty
sudo: required''

before_install:
  - sudo apt-get update
  - sudo apt-get install -y cmake

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest

