language: cpp
compiler:
  - gcc
  - clang

os:
  -linux

dist: trusty
sudo: required''

before_install:
  - sudo apt-get update
  - sudo apt-get install -y cmake

script:
  - cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install
  - cmake --build _build
  - cmake --build _build --target install

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
